[package]
name = "ecochain_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.10.0"
candid = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
